"""Regenerate every figure and rewrite stats.md.

    pixi run python postprocessing/make_all.py

stats.md is the numeric source of truth for RESULTS.md: every number quoted in the prose there
must appear here, and both are produced from codec/results/benchmark.jsonl plus the committed
data/*.json. Nothing in this folder is typed in from memory.

Layer-weight figures additionally need data/layer_weights.json, which extract_layer_weights.py
writes from local checkpoints. That file is committed, so this script runs on a fresh clone; re-run
the extractor after training more steps.
"""

from __future__ import annotations

import datetime as dt
import importlib
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

# (module, figure basename) in the order they appear in RESULTS.md.
FIGURES = [
    ("plot_trajectories", "arm_trajectories"),
    ("plot_decomposition", "gap_decomposition"),
    ("plot_metric_panel", "metric_panel"),
    ("plot_metric_signature", "metric_signature"),
    ("plot_layer_weights", "layer_weight_shares"),
]


def main() -> None:
    from lib import save

    sections: list[str] = []
    for module_name, basename in FIGURES:
        module = importlib.import_module(module_name)
        fig, stats = module.build()
        path = save(fig, basename)
        print(f"  {path.relative_to(HERE.parent)}")
        sections.append(f"<!-- from {module_name}.py -->\n\n{stats}")

    stamp = dt.datetime.now(tz=dt.UTC).date().isoformat()
    out = HERE / "stats.md"
    out.write_text(
        "# Generated numbers\n\n"
        f"**Generated by `make_all.py` on {stamp}. Do not edit.**\n\n"
        "Every figure in `RESULTS.md` is drawn from these values, and every number quoted in that\n"
        "file's prose appears here. Sources: `codec/results/benchmark.jsonl` (written by\n"
        "`kmira.benchmark.eval_codec` at scoring time) and `data/*.json`.\n\n"
        "---\n\n" + "\n\n---\n\n".join(sections)
    )
    print(f"  {out.relative_to(HERE.parent)}")


if __name__ == "__main__":
    main()
